# Generated by Django 3.1.6 on 2021-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210217_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
