# Generated by Django 3.1.6 on 2021-02-17 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beats', models.ManyToManyField(blank=True, related_name='_gameelement_beats_+', through='gameElements.ElementBeat', to='gameElements.GameElement')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('element_user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_element_1', to='gameElements.gameelement')),
                ('element_user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_element_2', to='gameElements.gameelement')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user_1', to='users.gameuser')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user_2', to='users.gameuser')),
            ],
        ),
        migrations.AddField(
            model_name='elementbeat',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat', to='gameElements.gameelement'),
        ),
        migrations.AddField(
            model_name='elementbeat',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_beats', to='gameElements.gameelement'),
        ),
    ]
