# Generated by Django 3.1.6 on 2021-02-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('gameElements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='match_winner', to='users.gameuser'),
            preserve_default=False,
        ),
    ]
