# Generated by Django 3.1.6 on 2021-02-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameElements', '0003_auto_20210217_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='element_user_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_element_1', to='gameElements.gameelement'),
        ),
        migrations.AlterField(
            model_name='match',
            name='element_user_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_element_2', to='gameElements.gameelement'),
        ),
    ]
